#读写分离
spring:
  #shardingsphere 分库分表配置
  shardingsphere:
    datasource:
      names: ds0,ds1,ds2
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.2.217:3306/ds0?allowMultiQueries=true
        username: opsa
        password: pass123456
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.2.217:3306/ds1?allowMultiQueries=true
        username: opsa
        password: pass123456
      ds2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.2.217:3306/ds2?allowMultiQueries=true
        username: opsa
        password: pass123456
    # 数据库读写分离
    masterslave:
      master-data-source-name: ds0
      slave-data-source-names: [ds1,ds2]
      name: ms
      load-balance-algorithm-type: round_robin
    props:
      sql:
        show: true # 打印分片后真实执行的sql